<!DOCTYPE html>
<html>
<head>

    <title>Emre Buyukada- Emre Isleyen</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div id="list">
           </div> 
        <div>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <asp:Button ID="kapat" runat="server" Text="Oturumu Kapat" Width="196px" />
        </div>        
            <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
        <br />
<input type="text" name="txt" value="software engineer" id="nick">
  <input type="button" name="button" id="giris" value="giris">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <br />
    <br />
      
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="txtJob1" value="MESAJ" id="mesaj" size="20">
     <input type="text" name="txtJob" value="kisi" id="kisi">
  <input type="button" name="button" id="gonder" value="gonder">
    <!--Script references. -->
    <!--Reference the jQuery library. -->
        <script src="/scripts/ip.js"> </script>
    <script src="/scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="/scripts/jquery.signalR-2.2.3.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
       
      
        var kapat = document.getElementById("kapat");//sisteme giris butonu
        kapat.onclick = function () {
            cikis();
            window.close()
           // alert("Oturum Kapatılıyor...");
            
        }
     

        
        var btnSelam=document.getElementById("giris");//sisteme giris butonu
        btnSelam.onclick = function () {
          //  window.alert("Siteme Hoþgeldiniz");
            var adi = document.getElementById("nick").value;
            var ip = document.getElementById('list').innerHTML;
            
            var yeniElement2 = document.createElement("RadioButton");
            document.body.appendChild(yeniElement2);
            ipkayit(ip);
            join(adi);
            fnAcKapa('nick');
            fnAcKapa('giris');
          //  fnAcKapa('mesaj');fnAcKapa('kisi');fnAcKapa('label1'); fnAcKapa('gonder');
        }
    
       
        function fnAcKapa(controlId)
        {
            var control = document.getElementById(controlId);
            if(control.style.visibility == "visible" || control.style.visibility == "")
                control.style.visibility = "hidden";
            else
                control.style.visibility = "visible";
            
        }
        var txt=0;
        function mesajkontrol() {
            if (txt == 0) {
                var r = confirm("Mesaj gelsin mi ?");
                if (r == true) {
                    txt = 1;
                } else {
                    txt = 0;
                }
            }
        }
            // Declare a proxy to reference the hub.
            var chat = $.connection.postHub;
            
            chat.client.Test = function (message) {
                mesajkontrol();
                if (txt == 1)
                {
                    document.getElementById('Label1').innerHTML += message + "<br>";
                }
              
                
              
            };
            chat.client.Test1 = function (kisi) {
                
                document.getElementById('Label2').innerHTML = kisi;
                //  console.log(message);
            };
      
           

            $.connection.hub.start().done(function () {
            });
           
            function yukle() {
                var control = document.getElementById('nick');
                if (control.style.visibility == "hidden")
                {
                    //alert("durum bu");
                    chat.server.yukle();
                }
               
            };

            window.setInterval(function () {
                
                yukle();
                // Burada fonksiyonlarınızı çağırın
            }, 15000);
            function sendMessage(message, to) {
                chat.server.receiveMessage(message, to);
            };

            function cikis() {
                var ip = document.getElementById('list').innerHTML;
                ipkayit(ip);
                chat.server.cikis();
            }

            function join(username) {

                chat.server.join(username);
            };
            function ipkayit(ip) {
                chat.server.ipkayit(ip);
            };

            var gndr = document.getElementById("gonder");
            gndr.onclick = function () {
                var control = document.getElementById('nick');
                if (control.style.visibility == "hidden") {
                    // window.alert("Siteme Hoşgeldiniz");
                    var mesaj = document.getElementById("mesaj").value;
                    var kisi = document.getElementById("kisi").value;
                    var nick = document.getElementById("nick").value;
                    mesaj = nick + "  -  " + mesaj;
                    if (kisi == nick)
                    { }
                    else
                    {

                        document.getElementById('Label1').innerHTML += mesaj + "<br>";
                        chat.server.receiveMessage(mesaj, kisi);
                    }




                }
                else
                {
                    alert("sisteme giris yapiniz...");
                }
            }
            
    </script>
 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <asp:Label ID="Label1" runat="server" Text=""></asp:Label>
        <div style="margin-left: 280px">
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
         
        <div style="margin-left: 280px">
        </div>
    </form>
</body>
</html>